name: Release

on:
  push:
    branches:
      - main


permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: install semantic release 
        run: python3 -m pip install python-semantic-release
      
      - name: check installation of pysemver
        run: python-semantic-release --version 

      - name: run version/publish command
        env:
          # REQUIRED: Provides authentication to create/push tags
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          semantic-release version
          semantic-release publish
      # - name: run version command
      #   run: semantic-release version
      #
      # - name: run publish command
      #   env:
      #     # REQUIRED: Provides authentication to create/push tags
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: semantic-release publish 

